### ISSUE TITLE
Trivia Crack tab runs out of memory after being left open for a long time

### ISSUE THREAD

**Issue by arpsmack** [arpsmack/trivia-crack-auto-card-clicker#1]
I often leave this running in the background for days and the tab will sometimes run out of memory, preventing the cards from activating.

**Comment by arpsmack** [comment]
I think the auto-reload functionality is enough to deal with this (along with running an ad-blocker).

**Comment by sk666** [comment]
Hi Matt!

Your last version seems to work verry well, I had previously an issue with the auto-reload but you fixed it and it works like a charm.

Thank you and have a nice day :)


Envoyé depuis mon appareil Samsung Galaxy Note 4


-------- Message d'origine --------
De : Matt Arpidone <notifications@github.com>
Date : 13/06/2017 2:13 AM (GMT-05:00)
À : arpsmack/trivia-crack-auto-card-clicker <trivia-crack-auto-card-clicker@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [arpsmack/trivia-crack-auto-card-clicker] Trivia Crack tab runs out of memory after being left open for a long time (#1)


I think the auto-reload functionality is enough to deal with this (along with running an ad-blocker).
